---
- name: Install vim
  apt:
    name: vim
    state: latest

- name: Install tmux
  apt:
    name: tmux
    state: latest

- name: Install git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Upload deploy key
  no_log: True
  copy:
    content: "{{ ssl_key }}"
    dest: ~/.ssh/deploy
    owner: root
    group: root
    mode: 0600

# Change to new repo
- name: Checkout latest commit
  git:
    repo: "git@github.com:seagoj/amazon_api.git"
    dest: "{{ document_root }}/amazon_api"
    accept_hostkey: True
    key_file: /root/.ssh/deploy

- name: Install ruby
  apt:
    name: ruby
    state: latest

- name: Install Bundler
  command: gem install bundler
  args:
    creates: /usr/local/bin/bundler

- name: Install gems
  command: bundle install
  args:
    chdir: "{{ document_root }}"
    creates: Gemfile.lock

# - name: Prepare environment AWS_ACCESS_KEY_ID
#   lineinfile:
#     dest: /etc/environment
#     regexp: "^export AWS_ACCESS_KEY_ID=."
#     line: "export AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"

# - name: Prepare environment AWS_SECRET_ACCESS_KEY
#   lineinfile:
#     dest: /etc/environment
#     regexp: "^export AWS_SECRET_ACCESS_KEY=."
#     line: "export AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

# - name: Prepare environment AWS_ASSOCIATE_TAG
#   lineinfile:
#     dest: /etc/environment
#     regexp: "^export AWS_ASSOCIATE_TAG=."
#     line: "export AWS_ASSOCIATE_TAG={{ lookup('env', 'AWS_ASSOCIATE_TAG') }}"
